apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f kafka-docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f kafka-docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka-net: "true"
        io.kompose.service: kafka-ui
    spec:
      containers:
      - env:
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: kafka-cluster:9092  # Keep this for internal communication
        - name: KAFKA_CLUSTERS_0_NAME
          value: local-kafka
        - name: KAFKA_CLUSTERS_0_ZOOKEEPER
          value: zookeeper:2181
        image: gcr.io/music-analytics-project/kafka-ui:latest
        imagePullPolicy: ""
        name: kafka-ui
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
