apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f kafka-docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: "port"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: kafka-ui
